title: Jaemin Jeong's Homepage
logo: http://github.com/dscoool/dscoool.github.io/raw/main/assets/img/j_logo.png
description: 강사 정재민, 데이터사이언티스트, 인공지능/파이썬, <br/>취업진로지도, 국민대학교 소프트웨어융합대학원, 광주과학기술원 (GIST) 인공지능연구소, 서울대 
show_downloads: false
google_analytics: G-G3H4KZV2D8
theme: jekyll-theme-minimal
