title: Jaemin Jeong
logo: 
description: 정재민, 교수, 데이터사이언티스트, 인공지능/파이썬, <br/>취업진로지도, 국민대학교 소프트웨어융합대학원, 광주과학기술원, GIST, 서울대 
show_downloads: true
google_analytics: G-3NW1FL0N7N
theme: jekyll-theme-minimal
